name: Deploy-angular-githubpages-workflow

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.USER_GITHUB_TOKEN}}
          workflow: build-test.yml
          workflow_conclusion: success
          pr: ${{github.event.pull_request.number}}
          commit: ${{github.event.pull_request.head.sha}}
          name: deploy_dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: tweempus
